# -*- coding: utf-8 -*-
"""APPROXIMATING LAPLACE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfkLOP-p00TS03ttxldcHQB1VECgL0dl
"""

import numpy as np
import matplotlib.pyplot as plt

def solvelaplace(init_psi, alpha, N):
  psi_current = np.zeros((7,7))
  psi_bar = np.zeros((7,7))
  psi_next = np.zeros((7,7))
  psi_next[:,:] = init_psi
  rows,cols = init_psi.shape
  delta_x = 1/(cols-1)
  delta_y= 1/(rows-1)
  inv_delta_xs = (1/delta_x)**2
  inv_delta_ys = (1/delta_y)**2
  hist_values = np.zeros((N,3))
  psi_current[:,:]=init_psi
  for k in range(0,N):
    hist_values[k,0], hist_values[k,1], hist_values[k,2] = psi_current[1,1], psi_current[3,3], psi_current[5,5]
    for i in range(1,rows-1):
      for j in range(1,cols-1):
        psi_bar[i,j]=((psi_current[i+1,j]+psi_current[i-1,j])*inv_delta_xs + (psi_current[i,j+1]+psi_current[i,j-1])*inv_delta_ys)/(2*(inv_delta_ys+inv_delta_xs))
        psi_next[i,j] = (1-float(alpha))*psi_current[i,j] + float(alpha)*psi_bar[i,j]
        psi_current[:,:] = psi_next
  return psi_next, hist_values

initial_grid = np.zeros((7, 7))
initial_grid[0,:] = 1
initial_grid[:,0] = 1
initial_grid[-1,:] = 1
initial_grid[:,-1] = 1
solvelaplace(initial_grid,1.35,30)

import numpy as np

def solvelaplace(init_psi, alpha, N):
  #set initial values for matrices psi_current which is psi_m, psi_m+1 which is psi_next and psi_bar
  psi_current = np.zeros((7,7))
  psi_bar = np.zeros((7,7))
  psi_next = np.zeros((7,7))
  #preset the boundary values of the m+1 matrix as I will only be iterating within the matrix not including boundaries
  psi_next[:,:] = init_psi
  #set all variables relating to delta_x and y
  rows,cols = init_psi.shape
  delta_x = 1/(cols-1)
  delta_y= 1/(rows-1)
  inv_delta_xs = (1/delta_x)**2
  inv_delta_ys = (1/delta_y)**2
  hist_values = np.zeros((N,3))
  #also preset the initial matrix to match the inputted matrix
  psi_current[:,:]=init_psi
  #loop over the index m which is k in my case adding historical values of [1,1], [3,3], [5,5] which are actually [2,2], [4,4] and [6,6] respectively but numpy starts arrays at [0,0]
  for k in range(0,N):
    hist_values[k,0], hist_values[k,1], hist_values[k,2] = psi_current[1,1], psi_current[3,3], psi_current[5,5]
  #for each iteration of m modify the entire matrix by looping over i and j
    for i in range(1,rows-1):
      for j in range(1,cols-1):
        psi_bar[i,j]=((psi_current[i+1,j]+psi_current[i-1,j])*inv_delta_xs + (psi_current[i,j+1]+psi_current[i,j-1])*inv_delta_ys)/(2*(inv_delta_ys+inv_delta_xs))
        psi_next[i,j] = (1-float(alpha))*psi_current[i,j] + float(alpha)*psi_bar[i,j]
  #for the next loop set psi m to m+1
        psi_current[:,:] = psi_next
  return psi_next, hist_values
#set the initial grid with 0s on the left side and bottom as if it were mimicking the x and y axes if i were to leave increasing x and y with increasing i and j, the y = 0 outputs would be the top row as i = 0 is the top row
second_grid = np.zeros((7,7))
rowsl,colsl = second_grid.shape
delta_x = 1/(colsl-1)
delta_y= 1/(rowsl-1)
second_grid[-1,:] = 0
second_grid[:,0] = 0
for j in range(1,7):
  second_grid[0,j] = np.sinh(1)*np.sin(j*delta_x)
for p in range(0,6):
  second_grid[p,-1] = np.sinh(1-p*delta_y)*np.sin(1)
psi_final, conv_values = solvelaplace(second_grid, 1.35, 30)
def plot_convergence(N, hist_values):
  x = np.linspace(0,N,N)
  y,z,a = hist_values[:,0],hist_values[:,1], hist_values[:,2]
  plt.plot(x,y)
  plt.plot(x,z)
  plt.plot(x,a)
plot_convergence(30, conv_values)
print(psi_final)
def contour_plot(final_matrix):
  x = np.arange(0, final_matrix.shape[1]) * delta_x
  y = np.arange(0, final_matrix.shape[0]) * delta_y
  X,Y = np.meshgrid(x,y)
  Z = np.flipud(final_matrix)
  plt.figure()
  plt.contour(X,Y,Z, levels=200, cmap='viridis')
contour_plot(psi_final)