# -*- coding: utf-8 -*-
"""Gram Schmidt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1WRnzYR6-kMwbbL57U2AtNuxOqwV0q4
"""

import numpy as np
from numpy.polynomial import Polynomial
from numpy.polynomial.hermite import hermgauss

import numpy as np
from numpy.polynomial import Polynomial
from numpy.polynomial.hermite import hermgauss

def _print_poly(indices, coefs):
    #Prints p_{indices}(x) in a readable form, skipping near-zero terms. I've put this beforehand as the actual function requires it to output a clean result
    terms = []
    for j, c in enumerate(coefs):
        # skip coefficients that are just noise from rounding in these calcs
        if abs(c) < 1e-12:
            continue
        # format each term differently depending on the power j
        if j == 0:
            terms.append(f"{c:.6f}")        # constant term, just the number
        elif j == 1:
            terms.append(f"{c:.6f}x")       # linear term, no exponent needed
        else:
            terms.append(f"{c:.6f}x^{j}")  # higher powers, write x^j

    # join all surviving terms with " + " and print; if nothing survived print 0
    print(f"p_{indices}(x) = " + " + ".join(terms) if terms else f"p_{indices}(x) = 0")

def generate_orthonormal_polynomials(n_max):
    """
    Builds orthonormal polynomials p_0,...,p_{n_max} in L^2 with weight w(x) = exp(-x^2).

    Uses Gram-Schmidt on the monomial basis {1, x, x^2,...} with inner products
    computed via Gauss-Hermite quadrature -- this is exact for polys up to degree 2m-1,
    where m is the number of quadrature nodes, so m = n_max+1 is the minimum safe choice.

    Returns a list of Polynomials satisfying <p_i, p_j>_w = delta_ij.

    Gauss-Hermite quadrature replaces the integral
        ∫_{-∞}^{∞} f(x) e^{-x^2} dx
    with a finite sum
        sum_{i=1}^m w_i * f(x_i)
    where x_i are roots of Hermite polynomials and w_i are the corresponding weights.
    This is exact for polynomials up to degree 2m-1, so since f(x) = p(x)q(x) here,
    m = n_max+1 nodes is the minimum needed for exact inner products.
    """

    m = n_max + 1
    x_nodes, w_nodes = hermgauss(m)

    # weighted inner product using quadrature
    def inner_prod(p, q):
        return np.dot(w_nodes, p(x_nodes) * q(x_nodes))

    polys = []

    for k in range(n_max + 1):
        # make an array of dimensions n_max + 1 range ignores the final value and loop such that we find the kth polynomial associated with the x^kth monomial. 
        coef = np.zeros(k + 1)
        coef[k] = 1.0
        #this gives x^kth monomial as coefficients is [0,0,1.0,...] where the 1 is on the kth index of the list 
        v = Polynomial(coef)

        # subtract off components along previously found basis vectors and normalise
        for pj in polys:
            v = v - pj * inner_prod(v, pj)

        v = v / np.sqrt(inner_prod(v, v))
        polys.append(v)

        # print just this new polynomial
        _print_poly(k, v.coef)  # k is the indices of the current polynomial

    return


generate_orthonormal_polynomials(3)

