# -*- coding: utf-8 -*-
"""Gram Schmidt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1WRnzYR6-kMwbbL57U2AtNuxOqwV0q4
"""

import numpy as np
from numpy.polynomial import Polynomial
from numpy.polynomial.hermite import hermgauss

def generate_orthonormal_polynomials_minimal(n_max):
    """
    Generate orthonormal polynomials (degree 0..n_max) in L^2_w(R) with weight w(x)=exp(-x^2)
    using Gram–Schmidt on monomials and Gauss–Hermite quadrature.

    Purpose:
    - Return list [p0, p1, ..., pn_max] where each p_k is a Polynomial object
      normalized so <p_i, p_j>_w = ∫ p_i p_j e^{-x^2} dx = δ_{ij}.

    Inputs:
    - n_max : int
        Maximum polynomial degree to produce.

    Output:
    - polys : list of numpy.polynomial.Polynomial
        Orthonormal polynomials of degrees 0..n_max.
    Gauss–Hermite quadrature explanation:

    We want to compute integrals of the form
    ∫_{-∞}^{∞} f(x) e^{-x^2} dx

    Instead of integrating directly, Gauss–Hermite replaces this with
    sum_{i=1}^m w_i * f(x_i)

    where:
    x_i = special nodes (roots of Hermite polynomials)
    w_i = corresponding weights

    Key property:
      This is exact for all polynomials up to degree (2m - 1)

    In this code:
      f(x) = p(x) q(x)
    so we can compute inner products exactly (up to floating point error)
    without doing actual integration over (-∞, ∞)
    """

    # choose minimal exact quadrature: m = n_max + 1

    # Gauss–Hermite nodes and weights for weight exp(-x^2)
    x_nodes, w_nodes = hermgauss(m)

    # inner product via quadrature: <p,q> = sum w_i p(x_i) q(x_i)
    def inner_prod(p: Polynomial, q: Polynomial):
        return np.dot(w_nodes, p(x_nodes) * q(x_nodes))

    polys = []

    # Gram–Schmidt on monomials 1, x, x^2, ...
    for k in range(n_max + 1):
        # monomial x^k
        coef = np.zeros(k + 1)
        coef[k] = 1.0
        v = Polynomial(coef)

        # subtract projections onto earlier orthonormal polys
        for pj in polys:
            alpha = inner_prod(v, pj)
            v = v - pj * alpha

        # normalize (assumes non-degenerate; minimal implementation)
        norm = np.sqrt(inner_prod(v, v))
        v = v / norm

        polys.append(v)
        coefficient_list = []
        for i in range(len(polys)):
          coefficient_list = polys[i].coef   # extract coefficients
          print(f"p_{i}(x) = ", end="")

        # loop over coefficients and build polynomial
          for j in range(len(coefficient_list)):
            if abs(coefficient_list[j]) > 1e-12:   # ignore tiny numerical noise
              if j == 0:
                print(f"{coefficient_list[j]:.6f}", end="")
              elif j == 1:
                print(f" + {coefficient_list[j]:.6f}x", end="")
              else:
                print(f" + {coefficient_list[j]:.6f}x^{j}", end="")

            print()  # new line


generate_orthonormal_polynomials_minimal(3)

