# -*- coding: utf-8 -*-
"""animation heat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bquLcqebqo7Q83Gd1hdt89c2cX9B6rcq
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

def psi_heat(t, x, psi_0, a, kappa, N_terms):
  #This function computes the time evolution of the heat equation solution
  #with the series form:
  #psi(t, x) = psi_0 + sum_{k=0}^∞ A_k exp(-kappa q_k^2 t) g_k(x)
  #
  #Input:
  #t: time value or array of time values
  #x: spatial grid or value
  #psi_0: constant offset term
  #a: length of the interval [0, a]
  #kappa: diffusion constant
  #N_terms: number of terms kept in the truncated series
  #
  #Output:
  #psi: solution evaluated at the given t and x

  #convert inputs to numpy arrays
  t = np.asarray(t)
  x = np.asarray(x)

  #set up the values of k we will sum over
  k = np.arange(N_terms)

  qk = np.pi / a * (k + 0.5)

  #set the eigenfunctions g_k(x)
  gk = np.sqrt(2 / a) * np.sin(qk[:,None ] * x[ None, :])

  #set the coefficients A_k from the initial condition psi(x, 0) = 0
  Ak = -psi_0 * np.sqrt(2 / a) * a / (np.pi * (k + 0.5))

  #if t is a single value this is the fastest way to solve. This is necessary as the animation is done frame by frame so i will be inputting scalars into that
  if t.ndim == 0:
    series_sum = np.sum(
      Ak[:, None] * np.exp(-kappa * qk[:, None]**2 * t) * gk,
      axis=0
    )
    return psi_0 + series_sum
  else:
    #if t is an array which would be the general use case for the function this would be the slightly augmented method (presetting the value of psi as python gets angry)
    psi = np.zeros((len(t), len(np.atleast_1d(x))))

    for i in range(len(t)):
      series_sum = np.sum(
        Ak[:, None] * np.exp(-kappa * qk[:, None]**2 * t[i]) * gk,
        axis=0
      )

      psi[i, :] = psi_0 + series_sum

    return psi


def animate_solution(x, t_values, psi_0, a, kappa, N_terms):
  #This function animates the time evolution of psi(t, x)

  #set up figure and initial plot
  fig, ax = plt.subplots()
  y0 = psi_heat(t_values[0], x, psi_0, a, kappa, N_terms)
  line, = ax.plot(x, y0)

  #set axis limits and labels
  ax.set_xlim(x[0], x[-1])
  ax.set_ylim(np.min(y0), np.max(psi_heat(t_values[-1], x, psi_0, a, kappa, N_terms)))
  ax.set_xlabel("x")
  ax.set_ylabel("psi(t, x)")

  #update function for each frame
  def update(frame):
    y = psi_heat(t_values[frame], x, psi_0, a, kappa, N_terms)
    line.set_ydata(y)
    ax.set_title(f"t = {t_values[frame]:.3f}")
    return line,

  #create animation
  ani = FuncAnimation(fig, update, frames=len(t_values), interval=30, blit=False)

  plt.show()
  return ani


#example usage
psi_0 = 1.0
a = 1.0
kappa = 0.2
N_terms = 200

x = np.linspace(0, a, 200)
t_values = np.linspace(0, 2, 150)

ani = animate_solution(x, t_values, psi_0, a, kappa, N_terms)
from IPython.display import HTML
HTML(ani.to_jshtml())
#weird for t= 0 as initial condition does not match at boundary + finite terms
#small relaxation time