# -*- coding: utf-8 -*-
"""linear independence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEC-Hrz45I8klI4ixYd5Za4eP3Uotznq
"""

import numpy as np

def compute_linear_independence(A):
  #This function computes the Singular Value Decomposition of a matrix A and uses it to compute linear independence. This is a faster method than using determinant.
  #
  #Input:
  #A: (n x n) matrix with n vectors in columns that we want to test the independence of
  #
  #Output:
  #linearly indpendent or NOT linearly independent


  #determine matrix dimensions
  rows, cols = A.shape

  #compute A^T A which is symmetric
  ATA = np.dot(A.T, A)

  #compute eigenvalues and eigenvectors of A^T A
  eigenvalues, eigenvectors = np.linalg.eig(ATA)

  #take square root of eigenvalues to obtain singular values
  singular_values = np.sqrt(np.abs(eigenvalues))

  #sort singular values in descending order and reorder eigenvectors accordingly
  sort_indices = np.argsort(singular_values)[::-1]
  singular_values = singular_values[sort_indices]
  V = eigenvectors[:, sort_indices]

  #construct diagonal matrix S
  S = np.zeros((cols, cols))
  for i in range(cols):
    S[i,i] = singular_values[i]

  max_singular = max(singular_values)
  if np.any(np.abs(np.diag(S)) < 1e-7*max(1.0, max_singular)):
    print("Vectors are NOT linearly independent")
  else:
    print("Vectors are linearly independent")
  return singular_values

B = np.array([
  [1,3,2],
  [2,6,4],
  [3,9,6]
])
compute_linear_independence(B)