# -*- coding: utf-8 -*-
"""Monte Carlo 1d simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5N1nxn0uwB4yaz-W8rXKs4FKHsc7T8P
"""

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Parameters (normalized units)
# -----------------------------
dt = 1e-3
n_steps = 15000
B = 2.0
q = -1.0         # charge
m = 1.0
gamma0 = 10.0

# Initial momentum
v0 = np.sqrt(1 - 1/gamma0**2)
p = np.array([0.4 * gamma0 * v0, 0.0, 0.9 * gamma0 * v0])
x = np.zeros(3)

# Monte Carlo interaction parameters
mean_free_path = 2.0
energy_loss_fraction = 0.1

# Storage
traj = np.zeros((n_steps, 3))
gamma_hist = np.zeros(n_steps)
z_vals = []

def gamma(p):
    return np.sqrt(1 + np.dot(p, p))

def velocity(p):
    return p / gamma(p)

def boris_push(p, B, dt):
    t = q * B * dt / 2
    s = 2 * t / (1 + t*t)
    p_minus = p
    p_prime = p_minus + np.cross(p_minus, t)
    return p_minus + np.cross(p_prime, s)

# Sample next interaction
remaining_path = np.random.exponential(mean_free_path)

# -----------------------------
# Main loop
# -----------------------------
for i in range(n_steps):
    traj[i] = x
    g = gamma(p)
    gamma_hist[i] = g

    # Magnetic field along y
    p = boris_push(p, np.array([0, B, 0]), dt)

    v = velocity(p)
    x += v * dt

    dz = abs(v[2]) * dt
    remaining_path -= dz

    if remaining_path <= 0:
        E_kin = g - 1
        dE = energy_loss_fraction * E_kin
        new_g = g - dE

        scale = np.sqrt((new_g**2 - 1) / (g**2 - 1))
        p *= scale


        z_vals.append(x[2])
        remaining_path = np.random.exponential(mean_free_path)

# -----------------------------
# Plots
# -----------------------------
plt.figure()
plt.plot(traj[:,2], traj[:,0])
plt.xlabel("z")
plt.ylabel("x")
plt.title("Particle trajectory (x vs z)")
plt.show()

plt.figure()
plt.plot(gamma_hist)
plt.xlabel("step")
plt.ylabel("gamma")
plt.title("Energy evolution")
plt.show()

plt.figure()
plt.hist(z_vals, bins=40)
plt.xlabel("z")
plt.ylabel("interactions")
plt.title("Interaction depth distribution")
plt.show()